namespace: default

# For latest versions see:
# https://artifacthub.io/packages/search?org=kamu
kamuApiServer:
  enabled: false
  chart: kamu/kamu-api-server
  version: "0.75.0"

kamuWebUi:
  enabled: false
  chart: kamu/kamu-web-ui
  version: "0.58.1"

jupyterHub:
  enabled: false
  chart: jupyterhub/jupyterhub
  version: "3.2.1"

minio:
  enabled: false
  chart: kamu/minio-devel
  version: "0.1.1"

qdrant:
  enabled: false
  chart: qdrant/qdrant
  version: "1.13.4"

superset:
  enabled: false
  chart: superset/superset
  version: "0.10.14"
